name: Snyk
on:
  push:
    branches:
      - main
      - integrate-snyk-9db1f33b1cbbf5dc
  workflow_dispatch: 
jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: the-guardian-cuu
      SKIP_NODE: true
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
